name: Sourcery Review

on: [push, pull_request]

jobs:
  sourcery:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Sourcery
        run: pip install sourcery

      - name: Run Sourcery
        run: sourcery review .
